// Generated by scripts/update-app-version.mjs. Do not edit manually.
export const APP_VERSION = "1.2.3";
export const APP_VERSION_LABEL = `Versão atual ${APP_VERSION}`;
export const APP_LAST_UPDATED_AT = "2026-08-22T10:37:19.777Z";
export const APP_LAST_UPDATED_LABEL = "22/08/2026";
export const APP_RELEASE_SHA = "602b903390eb2b708c128426b95b414da4697f7b";
export const APP_RELEASE_ID = "tarja-c2-revisao-production-2026-08-22";
