// Generated by scripts/update-app-version.mjs. Do not edit manually.
export const APP_VERSION = "1.1.9";
export const APP_VERSION_LABEL = `Versão atual ${APP_VERSION}`;
export const APP_LAST_UPDATED_AT = "2026-08-21T16:13:10.165Z";
export const APP_LAST_UPDATED_LABEL = "21/08/2026";
export const APP_RELEASE_SHA = "5c980102cb9789b808ed8d0362f58e0c2abbe875";
export const APP_RELEASE_ID = "release-production-home-campanha2-evolucao-kpi-2026-08-21";
