// Generated by scripts/update-app-version.mjs. Do not edit manually.
export const APP_VERSION = "1.1.2";
export const APP_VERSION_LABEL = `Versão atual ${APP_VERSION}`;
export const APP_LAST_UPDATED_AT = "2026-07-08T09:56:43.644Z";
export const APP_LAST_UPDATED_LABEL = "08/07/2026";
